// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/micro-writer.proto

package microwriter

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MicroWriter service

func NewMicroWriterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MicroWriter service

type MicroWriterService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (MicroWriter_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (MicroWriter_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (MicroWriter_BidiStreamService, error)
}

type microWriterService struct {
	c    client.Client
	name string
}

func NewMicroWriterService(name string, c client.Client) MicroWriterService {
	return &microWriterService{
		c:    c,
		name: name,
	}
}

func (c *microWriterService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "MicroWriter.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *microWriterService) ClientStream(ctx context.Context, opts ...client.CallOption) (MicroWriter_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "MicroWriter.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &microWriterServiceClientStream{stream}, nil
}

type MicroWriter_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type microWriterServiceClientStream struct {
	stream client.Stream
}

func (x *microWriterServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *microWriterServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *microWriterServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microWriterServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microWriterServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microWriterServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *microWriterService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (MicroWriter_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "MicroWriter.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &microWriterServiceServerStream{stream}, nil
}

type MicroWriter_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type microWriterServiceServerStream struct {
	stream client.Stream
}

func (x *microWriterServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *microWriterServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *microWriterServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microWriterServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microWriterServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microWriterServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *microWriterService) BidiStream(ctx context.Context, opts ...client.CallOption) (MicroWriter_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "MicroWriter.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &microWriterServiceBidiStream{stream}, nil
}

type MicroWriter_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type microWriterServiceBidiStream struct {
	stream client.Stream
}

func (x *microWriterServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *microWriterServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *microWriterServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microWriterServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microWriterServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microWriterServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *microWriterServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MicroWriter service

type MicroWriterHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, MicroWriter_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, MicroWriter_ServerStreamStream) error
	BidiStream(context.Context, MicroWriter_BidiStreamStream) error
}

func RegisterMicroWriterHandler(s server.Server, hdlr MicroWriterHandler, opts ...server.HandlerOption) error {
	type microWriter interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type MicroWriter struct {
		microWriter
	}
	h := &microWriterHandler{hdlr}
	return s.Handle(s.NewHandler(&MicroWriter{h}, opts...))
}

type microWriterHandler struct {
	MicroWriterHandler
}

func (h *microWriterHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.MicroWriterHandler.Call(ctx, in, out)
}

func (h *microWriterHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.MicroWriterHandler.ClientStream(ctx, &microWriterClientStreamStream{stream})
}

type MicroWriter_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type microWriterClientStreamStream struct {
	stream server.Stream
}

func (x *microWriterClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microWriterClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microWriterClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microWriterClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microWriterClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *microWriterHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.MicroWriterHandler.ServerStream(ctx, m, &microWriterServerStreamStream{stream})
}

type MicroWriter_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type microWriterServerStreamStream struct {
	stream server.Stream
}

func (x *microWriterServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microWriterServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microWriterServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microWriterServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microWriterServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *microWriterHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.MicroWriterHandler.BidiStream(ctx, &microWriterBidiStreamStream{stream})
}

type MicroWriter_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type microWriterBidiStreamStream struct {
	stream server.Stream
}

func (x *microWriterBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *microWriterBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *microWriterBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *microWriterBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *microWriterBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *microWriterBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
